export const translations = {
    nl: {
        langButton: "🇬🇧 English",
        portfolioTitle: "Mijn Portfolio",
        navHome: "Home",
        navProjects: "Projecten",
        navLanguages: "Programmeertalen",
        aboutTitle: "Over het project",
        techTitle: "Technologieën",
        backLink: "Terug naar projecten",

        heading: "Wie ben ik?",
        bio: `Hoi, ik ben <strong> Jonah Beijer </strong>
            Ik ben 20 jaar en een enthousiaste developer met een passie voor het bouwen van webapplicaties en apps. Ik ben altijd leergierig en sta open om mezelf verder te ontwikkelen, of dat nu betekent dat ik nieuwe technieken leer of bijspijker waar nodig. Ik kijk er enorm naar uit om tijdens mijn stage nieuwe ervaringen op te doen, mijn vaardigheden te verbeteren en te ontdekken wat het werkveld allemaal te bieden heeft.`,

        navbarTitle: "Mijn Portfolio",
        homeLink: "Home",
        projectsLink: "Projecten",
        programmingLanguagesLink: "Programmeertalen",
        projectCardDescGamemaniac: "Mijn allereerste website, gebouwd met enkel HTML en CSS.",
        projectCardDescAnimeCollection: "Een anime-verzamelsite met een CRUD-systeem en database.",
        projectCardDescMuziekGallary: "Een muziekgalerij-website gemaakt met HTML, CSS, JavaScript en PHP.",
        projectCardDescEerste2DGame: "Mijn eerste 2D game gemaakt met Excalibur.js en JavaScript.",
        projectCardDescSpinShare: "Een Laravel-platform waar gebruikers hun favoriete albums kunnen delen.",
        projectCardDescMeerkatGaming: "Een gaming community site gebouwd met React en moderne webtechnologieën.",
        projectDetailsLink: "Meer informatie",
        projectsTitle: "Mijn Projecten",

        gamemaniacTitle: "Gamemanic - Projectdetails",
        gamemaniacAbout: "Gamemanic is mijn eerste project, gemaakt met alleen HTML en CSS. Het is een simpele website die ik heb gebouwd om meer te leren over webontwikkeling en het creëren van gebruikersinterfaces.",

        animeCollectionTitle: "Anime Collection - Projectdetails",
        animeCollectionAbout: "Anime Collection is een dynamische website waar gebruikers hun favoriete anime-series kunnen toevoegen, bewerken en verwijderen. De site maakt gebruik van PHP en MySQL voor back-end functionaliteit en is voorzien van een gebruiksvriendelijke interface.",

        meerkatGamingTitle: "Meerkat Gaming - Projectdetails",
        meerkatGamingAbout: "Meerkat Gaming is een gaming-gerelateerde website gemaakt in teamverband. De focus lag op samenwerking, het verdelen van taken, en het toepassen van frontend- én backendtechnieken. De site bevat nieuws, reviews en een overzicht van populaire games.",

        musicGalleryTitle: "Muziek Gallery - Projectdetails",
        musicGalleryAbout: "Muziek Gallery is een interactieve webapplicatie waar gebruikers muziek kunnen ontdekken en bekijken in een galerij-achtige omgeving. Het project combineert frontend en backend technologieën en maakt gebruik van PHP en JavaScript.",
        viewGitHub: "Bekijk op GitHub",
        viewWebsite: "Bekijk de website",

        gamePageTitle: "Game - Projectdetails",
        gameAboutText: `Dit is een spel dat ik heb ontwikkeld met behulp van Excalibur.js, een 2D game-engine voor JavaScript. In het spel nemen twee spelers het tegen elkaar op in een racespel waarin snelheid en timing cruciaal zijn. Ik heb gewerkt met physics, collision detection en sprite-animaties om de game soepel te laten verlopen.`,
        spinShareTitle: "SpinShare - Projectdetails",
        spinShareAbout: "SpinShare is een sociale muziekapplicatie waarbij gebruikers hun favoriete albums kunnen delen, beoordelen en ontdekken. Het project is volledig gebouwd met Laravel en bevat gebruikersauthenticatie, albumbeheer, een admin-paneel en filter- en zoekfuncties.",
        traitsTitle: "Eigenschappen",
        trait1: "Vriendelijk",
        trait2: "Leergierig",
        trait3: "Loyaal",
        trait4: "Eerlijk",
        trait5: "Meedenkend",
        trait6: "Open-minded",

        visionTitle: "Toekomstvisie",
        vision1: "AI-integratie in webapps",
        vision2: "Progressieve Web Apps",
        vision3: "3D web development",
        hobbiesTitle: "Hobby's",
        hobby1: "Anime kijken",
        hobby2: "Gamen",
        hobby3: "Raves",
        educationTitle: "Opleiding",
        educationText: "Hogeschool Rotterdam CMGT",
        vintageAppTitle: "Vintage Store Finder",
        vintageAbout: "Een mobiele app ontwikkeld met React Native en Expo die vintage liefhebbers helpt bij het vinden van unieke tweedehands winkels. De app toont real-time openingsuren, locaties en laat gebruikers hun favoriete winkels opslaan.",
        featuresTitle: "Belangrijkste functies",
        liveLocationsTitle: "Live Locaties",
        liveLocationsDesc: "Toont alle vintage winkels in de buurt op een interactieve kaart",
        favoritesTitle: "Favorieten",
        favoritesDesc: "Opslaan van favoriete winkels met offline toegang",
        techHighlightsTitle: "Technische highlights",
        realtimeUpdatesTitle: " Real-time updates",
        realtimeUpdatesDesc: "Firebase Firestore voor live synchronisatie van winkelgegevens en openingsuren",
        notificationsTitle: " Notificaties",
        notificationsDesc: "Push notificaties voor favoriete winkels die binnenkort sluiten",
        viewCode: "Bekijk code",
        demoApp: "Demo app",
        llmChatbotTitle: "AI Nieuws Analist",
        chatbotImageAlt: "Chatbot interface",
        llmAbout: "Een geavanceerde chatbot ontwikkeld met Azure OpenAI, geïntegreerd met een nieuws-API en vector databases. De AI kan:",
        feature1: "Real-time nieuws analyseren",
        feature2: "Verbanden leggen tussen verschillende bronnen",
        feature3: "Contextuele antwoorden genereren",
        nlpTitle: "NLP Verwerking",
        nlpDesc: "Geavanceerde tekstanalyse met Azure OpenAI",
        vectorTitle: "Vector Database",
        vectorDesc: "Semantische zoekfuncties met FAISS indexering",
        apiIntegrationTitle: " API Integratie",
        apiIntegrationDesc: "Real-time nieuwsdata ophalen van 15+ bronnen",
        contextualTitle: " Contextueel Begrip",
        contextualDesc: "Semantische matching met 95% nauwkeurigheid",
        gamemaniacFeature1: "Mobile-first ontwerp",
        gamemaniacFeature2: "CSS Grid en Flexbox lay-out",
        gamemaniacFeature3: "Semantische HTML structuur",
        responsiveTitle: "Responsive Design",
        responsiveDesc: "Optimaal voor alle schermgroottes",
        responsiveLayoutTitle: "📱 Responsive Layout",
        responsiveLayoutDesc: "Werkt op alle apparaten en browsers",
        performanceTitle: "⚡ Performant",
        performanceDesc: "100/100 Lighthouse score",
        designTitle: "Modern Design",
        designDesc: "CSS Animaties en transitions",
        semanticTitle: "Semantische HTML",
        semanticDesc: "Goede SEO-praktijken",
        animeFeature1: "CRUD-functionaliteit",
        animeFeature2: "Database-integratie",
        animeFeature3: "User authentication",
        dbTitle: "Database Management",
        dbDesc: "MySQL voor dataopslag",
        securityTitle: "Beveiliging",
        securityDesc: "Gehashte wachtwoorden",
        crudTitle: "🔧 CRUD Operations",
        crudDesc: "Volledige data management mogelijkheden",
        apiTitle: "🚀 API Ready",
        apiDesc: "RESTful endpoints voor integratie",
        htmlTag: "HTML",
        cssTag: "CSS",
        phpTag: "PHP",
        mysqlTag: "MySQL",
        animeCollectionImageAlt: "Anime Collection schermafbeelding",
        musicFeature1: "Audio player integratie",
        musicFeature2: "Dynamische content loading",
        musicFeature3: "Responsive grid layout",
        audioTitle: "Audio Player",
        audioDesc: "Inline audio playback",
        gridTitle: "Grid System",
        gridDesc: "Responsive card layout",
        performanceTitle2: "⚡ Prestaties",
        performanceDesc2: "Snelle laadtijden door caching",
        dynamicTitle: "🎛 Dynamisch",
        dynamicDesc: "Real-time content updates",
        musicGalleryImageAlt: "Muziek Gallery schermafbeelding",
        physicsTitle: "Physics Engine",
        physicsDesc: "Realistische bewegingen en botsingen",
        multiplayerTitle: "Multiplayer",
        multiplayerDesc: "Twee spelers lokaal",
        excaliburTag: "Excalibur",
        collisionTitle: "🎮 Collision System",
        collisionDesc: "Geavanceerde botsingsdetectie",
        animationTitle: "🖌️ Animations",
        animationDesc: "Vloeiende sprite animaties",
        videoNotSupported: "Je browser ondersteunt de video tag niet.",
        gameEngineText: "Dit is een spel dat ik heb ontwikkeld met behulp van",
        gameDescriptionText: "een 2D game-engine voor JavaScript. In het spel nemen twee spelers het tegen elkaar op in een racespel waarin snelheid en timing cruciaal zijn. Ik heb gewerkt met physics, collision detection en sprite-animaties om de game soepel te laten verlopen.",
        spinFeature1: "Gebruikersauthenticatie",
        spinFeature2: "Albumbeheer systeem",
        spinFeature3: "Admin dashboard",
        authTitle: "Authenticatie",
        authDesc: "Veilig inlog- en registratiesysteem",
        albumTitle: "Albumbeheer",
        albumDesc: "CRUD-functionaliteit voor albums",
        mvcTitle: "🏗️ MVC Architectuur",
        mvcDesc: "Gestructureerde code-organisatie",
        apiTitle2: "🔌 REST API",
        apiDesc2: "Integratie met externe services",
        laravelTag: "Laravel",
        tailwindTag: "Tailwind CSS",
        sqliteTag: "SQLite",
        spinShareImageAlt: "SpinShare schermafbeelding",

        meerkatFeature1: "Team collaboration tools",
        meerkatFeature2: "Real-time updates",
        meerkatFeature3: "User profiles",
        communityTitle: "Community Hub",
        communityDesc: "Discussie forums en groepen",
        realtimeTitle: "Real-time",
        realtimeDesc: "Live updates en notificaties",
        scalableTitle: "🚀 Schaalbaar",
        scalableDesc: "Microservices architectuur",
        secureTitle: "🔒 Beveiligd",
        secureDesc: "JWT authenticatie",
        frontendLink: "Frontend Code",
        backendLink: "Backend Code",
        reactTag: "React",
        viteTag: "Vite",
        mongoTag: "MongoDB",
        jsxTag: "JSX",
        meerkatImageAlt: "Meerkat Gaming schermafbeelding",
        projectCardDescVintageApp: "stront",
        projectCardDescChatbot: "homo",
        resBeijerTitle: "ResBeijer - Projectdetails",
        resBeijerAbout: "Een afsprakenreserveringssysteem voor een elektrotechniekbedrijf met:",
        resFeature1: "Afspraakbeheer",
        resFeature2: "Unieke reserveringscodes",
        resFeature3: "Admin dashboard",
        bookingTitle: "Afspraken",
        bookingDesc: "Online reserveringssysteem",
        adminTitle: "Admin Paneel",
        adminDesc: "Afspraken beheren en afvinken",
        codeTitle: "🔑 Unieke Codes",
        codeDesc: "Automatische reserveringscode generatie",
        statusTitle: "📊 Status Tracking",
        statusDesc: "Real-time afspraakstatus updates",
        resBeijerImageAlt: "ResBeijer schermafbeelding",
        projectCardDescResBeijer: "Reserveringssysteem voor elektrotechniek bedrijf met admin paneel",
        recent: "Recentere werk",
        older: "Vroegere projecten",




    },

    en: {
        langButton: "🇳🇱 Nederlands",
        portfolioTitle: "My Portfolio",
        navHome: "Home",
        navProjects: "Projects",
        navLanguages: "Programming Languages",
        aboutTitle: "About the project",
        techTitle: "Technologies",
        backLink: "Back to projects",

        heading: "Who am i?",
        bio: `Hi, I’m Jonah Beijer 
I’m 20 years old and an enthusiastic developer with a strong passion for building web applications and apps. I’m always eager to learn and grow, whether that means picking up new skills or improving existing ones. I'm really looking forward to what my internship has to offer and everything I can learn from it along the way.

`,

        navbarTitle: "My Portfolio",
        homeLink: "Home",
        projectsLink: "Projects",
        programmingLanguagesLink: "Programming Languages",
        projectCardDescGamemaniac: "My very first website, built with only HTML and CSS.",
        projectCardDescAnimeCollection: "An anime collection site with CRUD functionality and database.",
        projectCardDescMuziekGallary: "A music gallery website made with HTML, CSS, JavaScript, and PHP.",
        projectCardDescEerste2DGame: "My first 2D game created with Excalibur.js and JavaScript.",
        projectCardDescSpinShare: "A Laravel-based platform where users can share their favorite albums.",
        projectCardDescMeerkatGaming: "A gaming community website built with React and modern technologies.",
        projectDetailsLink: "More details",
        projectsTitle: "My Projects",

        gamemaniacTitle: "Gamemanic - Project Details",
        gamemaniacAbout: "Gamemanic is my first project, made with just HTML and CSS. It’s a simple website I built to learn more about web development and creating user interfaces.",

        animeCollectionTitle: "Anime Collection - Project Details",
        animeCollectionAbout: "Anime Collection is a dynamic website where users can add, edit, and delete their favorite anime series. The site uses PHP and MySQL for backend functionality and features a user-friendly interface.",

        meerkatGamingTitle: "Meerkat Gaming - Project Details",
        meerkatGamingAbout: "Meerkat Gaming is a gaming-related website created as a team project. The focus was on collaboration, dividing tasks, and applying both frontend and backend techniques. The site includes news, reviews, and an overview of popular games.",

        musicGalleryTitle: "Music Gallery - Project Details",
        musicGalleryAbout: "Music Gallery is an interactive web application where users can explore and view music in a gallery-like setting. The project combines frontend and backend technologies, using PHP and JavaScript.",
        viewGitHub: "View on GitHub",
        viewWebsite: "View the website",

        gamePageTitle: "Game - Project Details",
        gameAboutText: `This is a game I developed using Excalibur.js, a 2D game engine for JavaScript. In the game, two players compete in a racing game where speed and timing are crucial. I worked with physics, collision detection, and sprite animations to ensure smooth gameplay.`,
        spinShareTitle: "SpinShare - Project Details",
        spinShareAbout: "SpinShare is a social music application where users can share, rate, and discover their favorite albums. The project is fully built with Laravel and includes user authentication, album management, an admin panel, and filter and search functionalities.",
        traitsTitle: "Traits",
        trait1: "Friendly",
        trait2: "Curious",
        trait3: "Loyal",
        trait4: "Honest",
        trait5: "thoughtful",
        trait6: "Open-minded",
        visionTitle: "Future Vision",
        vision1: "AI integration in web apps",
        vision2: "Progressive Web Apps",
        vision3: "3D web development",
        hobbiesTitle: "Hobbies",
        hobby1: "Watching anime",
        hobby2: "Gaming",
        hobby3: "Attending raves",
        educationTitle: "Education",
        educationText: "Rotterdam University CMGT",
        vintageAppTitle: "Vintage Store Finder",
        vintageAbout: "A mobile app developed with React Native and Expo that helps vintage lovers find unique thrift stores. The app shows real-time opening hours, locations, and allows users to save their favorite stores.",
        featuresTitle: "Key Features",
        liveLocationsTitle: "Live Locations",
        liveLocationsDesc: "Displays all nearby vintage stores on an interactive map",
        favoritesTitle: "Favorites",
        favoritesDesc: "Save favorite stores with offline access",
        techHighlightsTitle: "Technical Highlights",
        realtimeUpdatesTitle: "Real-time updates",
        realtimeUpdatesDesc: "Firebase Firestore for live synchronization of store data and opening hours",
        notificationsTitle: " Notifications",
        notificationsDesc: "Push notifications for favorite stores closing soon",
        viewCode: "View code",
        demoApp: "Demo app",
        llmChatbotTitle: "AI News Analyst",
        chatbotImageAlt: "Chatbot interface",
        llmAbout: "An advanced chatbot built with Azure OpenAI, integrated with news API and vector databases. The AI can:",
        feature1: "Analyze real-time news",
        feature2: "Connect different sources",
        feature3: "Generate contextual responses",
        nlpTitle: "NLP Processing",
        nlpDesc: "Advanced text analysis with Azure OpenAI",
        vectorTitle: "Vector Database",
        vectorDesc: "Semantic search with FAISS indexing",
        apiIntegrationTitle: " API Integration",
        apiIntegrationDesc: "Fetch real-time news from 15+ sources",
        contextualTitle: " Context Understanding",
        contextualDesc: "Semantic matching with 95% accuracy",
        gamemaniacFeature1: "Mobile-first design",
        gamemaniacFeature2: "CSS Grid & Flexbox layout",
        gamemaniacFeature3: "Semantic HTML structure",
        responsiveTitle: "Responsive Design",
        responsiveDesc: "Optimized for all screen sizes",
        responsiveLayoutTitle: "📱 Responsive Layout",
        responsiveLayoutDesc: "Works on all devices and browsers",
        performanceTitle: "⚡ Performance",
        performanceDesc: "100/100 Lighthouse score",
        designTitle: "Modern Design",
        designDesc: "CSS Animations & transitions",
        semanticTitle: "Semantic HTML",
        semanticDesc: "SEO best practices",
        animeFeature1: "CRUD functionality",
        animeFeature2: "Database integration",
        animeFeature3: "User authentication",
        dbTitle: "Database Management",
        dbDesc: "MySQL for data storage",
        securityTitle: "Security",
        securityDesc: "Hashed passwords",
        crudTitle: "🔧 CRUD Operations",
        crudDesc: "Full data management capabilities",
        apiTitle: "🚀 API Ready",
        apiDesc: "RESTful endpoints for integration",
        htmlTag: "HTML",
        cssTag: "CSS",
        phpTag: "PHP",
        mysqlTag: "MySQL",
        animeCollectionImageAlt: "Anime Collection screenshot",
        musicFeature1: "Audio player integration",
        musicFeature2: "Dynamic content loading",
        musicFeature3: "Responsive grid layout",
        audioTitle: "Audio Player",
        audioDesc: "Inline audio playback",
        gridTitle: "Grid System",
        gridDesc: "Responsive card layout",
        performanceTitle2: "⚡ Performance",
        performanceDesc2: "Fast loading times with caching",
        dynamicTitle: "🎛 Dynamic",
        dynamicDesc: "Real-time content updates",
        musicGalleryImageAlt: "Music Gallery screenshot",
        physicsTitle: "Physics Engine",
        physicsDesc: "Realistic movement and collisions",
        multiplayerTitle: "Multiplayer",
        multiplayerDesc: "Two-player local mode",
        excaliburTag: "Excalibur",
        collisionTitle: "🎮 Collision System",
        collisionDesc: "Advanced collision detection",
        animationTitle: "🖌️ Animations",
        animationDesc: "Smooth sprite animations",
        videoNotSupported: "Your browser does not support the video tag.",
        gameEngineText: "This is a game I developed using",
        gameDescriptionText: "a 2D game engine for JavaScript. In the game, two players compete in a racing game where speed and timing are crucial. I worked with physics, collision detection, and sprite animations to ensure smooth gameplay.",
        spinFeature1: "User authentication",
        spinFeature2: "Album management system",
        spinFeature3: "Admin dashboard",
        authTitle: "Authentication",
        authDesc: "Secure login and registration system",
        albumTitle: "Album Management",
        albumDesc: "CRUD functionality for albums",
        mvcTitle: "🏗️ MVC Architecture",
        mvcDesc: "Structured code organization",
        apiTitle2: "🔌 REST API",
        apiDesc2: "Integration with external services",
        laravelTag: "Laravel",
        tailwindTag: "Tailwind CSS",
        sqliteTag: "SQLite",
        spinShareImageAlt: "SpinShare screenshot",
        meerkatFeature1: "Team collaboration tools",
        meerkatFeature2: "Real-time updates",
        meerkatFeature3: "User profiles",
        communityTitle: "Community Hub",
        communityDesc: "Discussion forums and groups",
        realtimeTitle: "Real-time",
        realtimeDesc: "Live updates and notifications",
        scalableTitle: "🚀 Scalable",
        scalableDesc: "Microservices architecture",
        secureTitle: "🔒 Secure",
        secureDesc: "JWT authentication",
        frontendLink: "Frontend Code",
        backendLink: "Backend Code",
        reactTag: "React",
        viteTag: "Vite",
        mongoTag: "MongoDB",
        jsxTag: "JSX",
        meerkatImageAlt: "Meerkat Gaming screenshot",
        projectCardDescVintageApp: "shit",
        projectCardDescChatbot: "gay",
        resBeijerTitle: "ResBeijer - Project Details",
        resBeijerAbout: "An appointment reservation system for an electrical engineering company with:",
        resFeature1: "Appointment management",
        resFeature2: "Unique reservation codes",
        resFeature3: "Admin dashboard",
        bookingTitle: "Appointments",
        bookingDesc: "Online reservation system",
        adminTitle: "Admin Panel",
        adminDesc: "Manage and check off appointments",
        codeTitle: "🔑 Unique Codes",
        codeDesc: "Automatic reservation code generation",
        statusTitle: "📊 Status Tracking",
        statusDesc: "Real-time appointment status updates",
        resBeijerImageAlt: "ResBeijer screenshot",
        projectCardDescResBeijer: "Reservation system for electrical engineering company with admin panel",
        recent: "Recent work",
        older: "Older projects",

    }
};

export let currentLanguage = localStorage.getItem("language") || "nl";

export function setLanguage(lang) {
    updateNavAnimations();
    const t = translations[lang];
    document.documentElement.lang = lang;
    document.getElementById('langToggle').checked = lang === 'en';

    document.querySelectorAll('[data-translate]').forEach(el => {
        const key = el.getAttribute('data-translate');
        if (t[key]) el.textContent = t[key];
    });

    // HTML-content velden
    const innerHTMLMap = {
        bio: t.bio,
        gameAboutText: t.gameAboutText,
        spinShareAbout: t.spinShareAbout,
        gamemaniacAbout: t.gamemaniacAbout,
        educationText: t.educationText
    };

    Object.entries(innerHTMLMap).forEach(([id, content]) => {
        const el = document.getElementById(id);
        if (el) el.innerHTML = content;
    });

    // TextContent voor specifieke elementen
    const textContentMap = {
        langToggle: t.langButton,
        portfolioTitle: t.portfolioTitle,
        navHome: t.navHome,
        navProjects: t.navProjects,
        navLanguages: t.navLanguages,
        heading: t.heading,
        gamePageTitle: t.gamePageTitle,
        spinShareTitle: t.spinShareTitle,
        projectsTitle: t.projectsTitle,
        backLink: t.backLink,
        backToProjects: t.backLink,
        traitsTitle: t.traitsTitle,
        trait1: t.trait1,
        trait2: t.trait2,
        trait3: t.trait3,
        trait4: t.trait4,
        trait5: t.trait5,
        trait6: t.trait6,
        visionTitle: t.visionTitle,
        vision1: t.vision1,
        vision2: t.vision2,
        vision3: t.vision3,
        hobbiesTitle: t.hobbiesTitle,
        hobby1: t.hobby1,
        hobby2: t.hobby2,
        hobby3: t.hobby3,
        educationTitle: t.educationTitle

    };

    Object.entries(textContentMap).forEach(([id, content]) => {
        const el = document.getElementById(id);
        if (el) el.textContent = content;
    });

    localStorage.setItem("language", lang);
    document.dispatchEvent(new CustomEvent('languageChanged', { detail: lang }));
}

// Init language on page load
document.addEventListener("DOMContentLoaded", () => {
    setLanguage(currentLanguage);
    // Voeg deze regel toe:
    document.getElementById('langToggle').checked = currentLanguage === 'en';


});



export function updateNavAnimations() {
    document.querySelectorAll('.nav-link').forEach(link => {
        const text = link.textContent.trim();
        link.innerHTML = text.split('').map((char, index) =>
            `<span class="char" style="--delay: ${index * 30}ms">${char}</span>`
        ).join('');
    });
}

// Language switcher
document.getElementById("langToggle")?.addEventListener("change", (e) => {
    currentLanguage = e.target.checked ? 'en' : 'nl';
    setLanguage(currentLanguage);
});

